<Project>
  <PropertyGroup>
    <LangVersion>latest</LangVersion>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <TreatWarningsAsErrors>false</TreatWarningsAsErrors>
    <Company>brans IT solutions</Company>
    <Product>DCMtoGDTReports</Product>
    <Copyright>Â© brans IT solutions</Copyright>
    <Version>1.4.0</Version>
    <InvariantGlobalization>false</InvariantGlobalization>
  </PropertyGroup>
</Project>


